name: SearchIds
main: net.serenity.searchids.SearchIds
version: 2.2
commands:
    search:
        description: Search for item IDs and data values
        usage: /<command> <item to search for>
